spring:
  datasource:
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
#    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none # disable Hibernate schema initialization
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot/48222934#48222934

  data:
    rest:
      base-path: /api/admin
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
  cache:
    ehcache:
      config: classpath:/cache/ehcache.xml

cyclone:
  lunchvoting:
    voting-ends: 11-00 # HH-mm format