spring:
  datasource:
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
#    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none # disable Hibernate schema initialization
  data:
    rest:
      base-path: /api/admin
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true

cyclone:
  lunchvoting:
    voting-ends: 11-00 # HH-mm format