spring:
  datasource:
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
#    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none # disable Hibernate schema initialization


cyclone:
  lunchvoting:
    voting-ends: 11-00 # HH-mm format